services:
  nodered:
    build: .
    container_name: biblioteca_nodered
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
      - ./sql:/data/sql
    env_file:
      - .env
    environment:
      - TZ=America/Mexico_City
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    privileged: true

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: biblioteca_mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log
    environment:
      - TZ=America/Mexico_City

  postgres:
    image: postgres:15-alpine
    container_name: biblioteca_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Mexico_City
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
