# Conexión MQTT normal (para tus placas NodeMCU/ESP32)
listener 1883 0.0.0.0
allow_anonymous true

# Conexión WebSockets (para tu Dashboard en el navegador)
listener 9001 0.0.0.0
protocol websockets

